"""Stateful, requests-based SDK for authorized internal VGHKS queries."""

from typing import TYPE_CHECKING

from ._version import __version__
from .acquisition import acquire, assess_data
from .core.config import EarningsCredentials, PortalCredentials, RequestPolicy, SDKSettings
from .core.errors import (
    AccessReviewRequiredError,
    ApplicationSessionExpiredError,
    AuthenticationError,
    AuthExpiredError,
    AuthorizationError,
    ConfigurationError,
    ErrorInfo,
    LoginRejectedError,
    NotAuthenticatedError,
    NotFoundError,
    ParseError,
    PasswordChangeRequiredError,
    RequestError,
    SDKError,
    error_info,
)
from .models import (
    AcquisitionResult,
    AuthCheckReport,
    AuthCheckTarget,
    BinaryAsset,
    CaseDetail,
    ClinicalOrder,
    ConsultRecord,
    DataAssessment,
    EarningsReportContext,
    FormSnapshot,
    HtmlDocument,
    MedicationHistoryFilter,
    MedicationOrder,
    MutationReceipt,
    NumericHistoryFilter,
    NumericHistoryReport,
    NumericReport,
    NumericTable,
    OrderCategory,
    OrderDetail,
    OrderDetailRef,
    OrderHistoryFilter,
    OrderReport,
    OrderReportRef,
    OutpatientPatient,
    PacsImageRef,
    PacsStudy,
    PacsStudyRef,
    PasswordStatus,
    PatientBasicInfo,
    PatientDemographics,
    PatientSurgeryRecord,
    PdfAttachmentRef,
    PersonnelFilter,
    PersonnelOption,
    PersonnelOptions,
    PersonnelRecord,
    RegistrationRecord,
    ReviewCase,
    ReviewCaseFilter,
    ReviewCasePart,
    ReviewCaseRef,
    ReviewLoginInfo,
    ScannedRecord,
    SoapChronicPrescriptionPeriod,
    SoapDiagnosis,
    SoapMedication,
    SoapOrder,
    SoapRecord,
    SurgeryCase,
    SurgeryCaseFilter,
    SurgeryCaseRef,
    SurgeryCommand,
    SurgeryHistoryFilter,
    SurgeryNoteRef,
    SurgeryRecord,
    SurgeryScheduleProcedure,
    TextReportHistory,
    TreatmentRecord,
    UnsignedRecord,
    UploadHistory,
    VisitCase,
    VisitFilter,
    VisitHistoryRecord,
)
from .order_status import classify_order_execution
from .queries import Queries, QuerySpec
from .sdk import VghksSDK
from .search import (
    DoctorOpdPatientSource,
    MrnPatientSource,
    SoapMatchEvidence,
    SoapScanMatch,
    SoapSearch,
)
from .workflows import PatientRecordsResult, SoapScanResult, export_patient_records, scan_soap

if TYPE_CHECKING:
    from .live.config import LiveTestConfig


def __getattr__(name: str):
    # Keep the old import working without loading the test harness in SDK apps.
    if name == "LiveTestConfig":
        from .live.config import LiveTestConfig

        globals()[name] = LiveTestConfig
        return LiveTestConfig
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    "AccessReviewRequiredError",
    "AcquisitionResult",
    "ApplicationSessionExpiredError",
    "AuthCheckReport",
    "AuthCheckTarget",
    "AuthExpiredError",
    "AuthenticationError",
    "AuthorizationError",
    "BinaryAsset",
    "CaseDetail",
    "ClinicalOrder",
    "ConfigurationError",
    "ConsultRecord",
    "DataAssessment",
    "DoctorOpdPatientSource",
    "EarningsCredentials",
    "EarningsReportContext",
    "ErrorInfo",
    "FormSnapshot",
    "HtmlDocument",
    "LiveTestConfig",
    "LoginRejectedError",
    "MedicationHistoryFilter",
    "MedicationOrder",
    "MrnPatientSource",
    "MutationReceipt",
    "NotAuthenticatedError",
    "NotFoundError",
    "NumericHistoryFilter",
    "NumericHistoryReport",
    "NumericReport",
    "NumericTable",
    "OrderCategory",
    "OrderDetail",
    "OrderDetailRef",
    "OrderHistoryFilter",
    "OrderReport",
    "OrderReportRef",
    "OutpatientPatient",
    "PacsImageRef",
    "PacsStudy",
    "PacsStudyRef",
    "ParseError",
    "PasswordChangeRequiredError",
    "PasswordStatus",
    "PatientBasicInfo",
    "PatientDemographics",
    "PatientRecordsResult",
    "PatientSurgeryRecord",
    "PdfAttachmentRef",
    "PersonnelFilter",
    "PersonnelOption",
    "PersonnelOptions",
    "PersonnelRecord",
    "PortalCredentials",
    "Queries",
    "QuerySpec",
    "RegistrationRecord",
    "RequestError",
    "RequestPolicy",
    "ReviewCase",
    "ReviewCaseFilter",
    "ReviewCasePart",
    "ReviewCaseRef",
    "ReviewLoginInfo",
    "SDKError",
    "SDKSettings",
    "ScannedRecord",
    "SoapChronicPrescriptionPeriod",
    "SoapDiagnosis",
    "SoapMatchEvidence",
    "SoapMedication",
    "SoapOrder",
    "SoapRecord",
    "SoapScanMatch",
    "SoapScanResult",
    "SoapSearch",
    "SurgeryCase",
    "SurgeryCaseFilter",
    "SurgeryCaseRef",
    "SurgeryCommand",
    "SurgeryHistoryFilter",
    "SurgeryNoteRef",
    "SurgeryRecord",
    "SurgeryScheduleProcedure",
    "TextReportHistory",
    "TreatmentRecord",
    "UnsignedRecord",
    "UploadHistory",
    "VghksSDK",
    "VisitCase",
    "VisitFilter",
    "VisitHistoryRecord",
    "__version__",
    "acquire",
    "assess_data",
    "classify_order_execution",
    "error_info",
    "export_patient_records",
    "scan_soap",
]
