"""Typed boundaries shared by the extended adapters and public services."""

from collections.abc import Mapping
from typing import Any, Protocol

from .core.config import EarningsCredentials
from .models import (
    BinaryAsset,
    EarningsReportContext,
    FormSnapshot,
    HtmlDocument,
    OrderReport,
    OrderReportRef,
    ReviewCase,
    ReviewCaseFilter,
    ReviewCasePart,
    ReviewCaseRef,
    ReviewLoginInfo,
    SurgeryCase,
    SurgeryCaseFilter,
    SurgeryCaseRef,
    SurgeryNoteRef,
    TextReportHistory,
    UploadHistory,
)


class PatientQueriesProtocol(Protocol):
    def get_allergy(self, mrn: str) -> dict[str, Any]: ...
    def get_advance_directives(self, mrn: str) -> dict[str, Any]: ...
    def get_research_flags(self, mrn: str) -> dict[str, Any]: ...
    def get_bed_transfers(self, mrn: str) -> dict[str, Any]: ...
    def get_care_cases(self, mrn: str) -> dict[str, Any]: ...
    def get_text_report_history(
        self, mrn: str, department: str, days: int = 3650
    ) -> TextReportHistory: ...
    def get_text_report(self, reference: OrderReportRef) -> OrderReport: ...
    def get_upload_types(self) -> list[dict[str, str]]: ...
    def get_upload_history(
        self, mrn: str, main_type: str = "", days: str = "*"
    ) -> UploadHistory: ...


class ReviewsProtocol(Protocol):
    def get_login_info(self) -> ReviewLoginInfo: ...
    def get_options(self) -> dict: ...
    def get_doctors(self, department: str) -> list[dict]: ...
    def get_cases(self, filter: ReviewCaseFilter) -> list[ReviewCase]: ...
    def get_case(self, ref: ReviewCaseRef) -> ReviewCase: ...
    def get_orders(self, ref: ReviewCaseRef) -> ReviewCasePart: ...
    def get_attachments(self, ref: ReviewCaseRef) -> ReviewCasePart: ...
    def get_pacs(self, ref: ReviewCaseRef) -> ReviewCasePart: ...


class SurgeryCasesProtocol(Protocol):
    def get_case_departments(self) -> list[str]: ...
    def get_cases(self, filter: SurgeryCaseFilter) -> list[SurgeryCase]: ...
    def get_record_ref(self, ref: SurgeryCaseRef) -> SurgeryNoteRef | None: ...
    def download_record(self, ref: SurgeryNoteRef) -> BinaryAsset: ...


class SurgeryQueriesProtocol(Protocol):
    def get_patient_info(self, mrn: str) -> dict[str, Any]: ...
    def get_patient_consents(self, mrn: str) -> dict[str, Any]: ...
    def get_request_numbers(self, mrn: str) -> dict[str, Any]: ...
    def get_anticoagulants(self, mrn: str) -> dict[str, Any]: ...
    def get_sglt2(self, mrn: str) -> dict[str, Any]: ...
    def get_procedure_catalog(self) -> dict[str, Any]: ...
    def get_holidays(self) -> dict[str, Any]: ...
    def get_supply_model(self, key: str, department: str) -> dict[str, Any]: ...
    def get_consent_catalog(self) -> dict[str, Any]: ...
    def get_consent_template(self, name: str, department: str) -> dict[str, Any]: ...
    def resolve_consent_doctor(self, card_no: str) -> dict[str, Any]: ...
    def open_schedule_form(
        self, fields: Mapping[str, Any], *, mode: str = "edit"
    ) -> FormSnapshot: ...
    def open_consent_form(self, fields: Mapping[str, Any]) -> FormSnapshot: ...


class EarningsServiceProtocol(Protocol):
    def open_performance(self, credentials: EarningsCredentials) -> EarningsReportContext: ...
    def open_bonus(self, credentials: EarningsCredentials) -> EarningsReportContext: ...
    def get_report(
        self, context: EarningsReportContext, period: str | None = None
    ) -> HtmlDocument: ...
